[default]
db_dir = "."
confirmations = 6
lwd_url = "http://lightd1.pirate.black:9067"
poll_interval = 10
notify_host = "http://localhost:14142"
#fvk = "zxviews1qvadgejdqqqqpqxmqzjzsd3z8g9qu5vuwjwaqmh4525x9h25ey2x4chuxx3e29wkstlndadtqh58fcwq7ts0423es44pdvxrzfw55h8kcwcq9hlvmxlwucwanayrmexd2wtw7g8zaaz70029l6m43ymmsdsghwdkxw52zl4aqq462hul8w0dxh4eclpdudym69ke39w8ex9gl3770uxeanx6kfslyjx5z00hcjtvrur634vwk33g0dp6sgk0l4xkls3p8kafgyr3wxs2d808u"
#starting_height = 2000000

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"
